package publisher

import (
	"context"
	"errors"
	"time"

	apperr "github.com/thedavidweng/tg-drive-cli/core/errors"
	"github.com/thedavidweng/tg-drive-cli/core/fsmodel"
	"github.com/thedavidweng/tg-drive-cli/core/manifest"
	"github.com/thedavidweng/tg-drive-cli/core/pathcodec"
	"github.com/thedavidweng/tg-drive-cli/core/ports"
	"github.com/thedavidweng/tg-drive-cli/core/telegram"
)

// Config controls caption and manifest rendering.
type Config struct {
	SafeMediaCaptionUTF16Units int
	MarginUTF16Units           int
}

// Publisher publishes files to the virtual file tree and keeps their Telegram
// messages, machine records, and the local index consistent (ADR 0029). Each
// entry point is one intent:
//
//   - Render + PublishFile: a new ungrouped file.
//   - Render + PublishAlbum: a new media group, indexed all-or-nothing.
//   - Move, Repair: an existing file's record and caption rewritten.
//   - PrepareReindex + ReindexBatch, Reindex: index-only, no Telegram writes.
type Publisher struct {
	tg        telegram.Client
	fileIndex ports.FileIndex
	cfg       Config
}

// New creates a publisher.
func New(tg telegram.Client, fileIndex ports.FileIndex, cfg Config) *Publisher {
	return &Publisher{tg: tg, fileIndex: fileIndex, cfg: cfg}
}

// RenderRequest describes a new publication to render.
type RenderRequest struct {
	// Meta is the file metadata. Tags are generated by Render.
	Meta manifest.FileMeta
	// HumanPrefix is source text kept above the rendered caption block
	// (imports); empty renders the block alone. Only the comment carrier
	// renders it.
	HumanPrefix string
	// ManifestChatID selects the manifest carrier: empty for the legacy
	// in-channel reply, the linked discussion group's Telegram channel id
	// for the comment carrier (ADR 0018).
	ManifestChatID string
	// ExistingSlugs is the current parent|segment -> slug map. Render adds
	// the slugs it mints, so members rendered in turn share one map.
	ExistingSlugs map[string]string
}

// Rendition is the output of one rendering pass: the caption, the hashtag
// chain, and the slug maps of one publication. Only Render produces one, so
// the caption a caller sends with the media and the tags the publisher
// indexes cannot diverge.
type Rendition struct {
	meta             manifest.FileMeta
	caption          string
	slugMaps         []pathcodec.SlugMapping
	manifestChat     string
	legacyReply      string
	legacyNeedsReply bool
}

// Caption is the media caption to send with the upload.
func (r *Rendition) Caption() string { return r.caption }

// Meta is the rendered file metadata, tags included.
func (r *Rendition) Meta() manifest.FileMeta { return r.meta }

// FileRequest publishes a new ungrouped file whose media is already on
// Telegram with its rendered caption.
type FileRequest struct {
	// ChannelRowID is the local SQLite channel id.
	ChannelRowID int64
	// ChannelID is the Telegram channel id.
	ChannelID int64
	// FileID is the local SQLite files.id; 0 for a new row.
	FileID int64
	// MessageID is the Telegram media message id.
	MessageID int
	Rendition *Rendition
	// ReplaceFileID is an active file to mark as superseded.
	ReplaceFileID int64
	// Now is the RFC3339 timestamp to use; empty uses time.Now().
	Now string
}

// PublishResult is the result of a file publication.
type PublishResult struct {
	FileID        int64
	ManifestMsgID int
}

// AlbumRequest publishes a new media group whose members are already on
// Telegram. Members are staged rows (FileID > 0) in message order, rendered
// for one carrier; the inventory goes through the first member's.
type AlbumRequest struct {
	ChannelRowID int64
	ChannelID    int64
	GroupedID    int64
	Members      []AlbumMember
	Now          string
}

// AlbumMember is one member of a new media group.
type AlbumMember struct {
	FileID        int64
	MessageID     int
	Rendition     *Rendition
	ReplaceFileID int64
}

// AlbumResult reports a group publication. InventoryMsgID is set whenever
// the td-album:v1 inventory reached Telegram, including alongside an index
// error, so the caller's rollback can delete it.
type AlbumResult struct {
	InventoryMsgID int
}

// RecordRef locates the published record of an existing file.
type RecordRef struct {
	ChannelRowID int64
	ChannelID    int64
	FileID       int64
	MessageID    int
	// ManifestMsgID is the existing manifest message id — a reply or a
	// comment, per ManifestChatID — or 0 if none.
	ManifestMsgID  int
	ManifestChatID string
}

// ReindexRequest is a read-only re-indexing request.
type ReindexRequest struct {
	// ChannelRowID is the local SQLite channel id.
	ChannelRowID int64
	// FileID is the local SQLite files.id; 0 for a new row.
	FileID int64
	// MessageID is the Telegram media message id.
	MessageID int
	// ManifestMsgID is the existing manifest message id, or 0.
	ManifestMsgID int
	// ManifestChatID is the carrier peer of ManifestMsgID: empty for the
	// legacy in-channel reply, the discussion group id for comments
	// (ADR 0018).
	ManifestChatID string
	// Meta is the parsed metadata from a caption or manifest.
	Meta manifest.ParsedMeta
	// ExistingSlugs is the current parent|segment -> slug map.
	ExistingSlugs map[string]string
	// ReplaceFileID is an active file to mark as superseded in the same
	// commit.
	ReplaceFileID int64
	// Now is the RFC3339 timestamp to use; empty uses time.Now().
	Now string
}

// Reindexing is one ReindexRequest rendered into an index entry, ready to
// commit with ReindexBatch.
type Reindexing struct {
	req ports.FileIndexRequest
}

// ReindexResult is the result of a re-index.
type ReindexResult struct {
	FileID        int64
	ManifestMsgID int
}

func (p *Publisher) now(now string) string {
	if now != "" {
		return now
	}
	return time.Now().UTC().Format(time.RFC3339)
}

// Render runs the one rendering pass of a publication: hashtag chain, slug
// maps, and caption for the request's carrier.
func (p *Publisher) Render(req RenderRequest) (*Rendition, error) {
	if req.ExistingSlugs == nil {
		req.ExistingSlugs = map[string]string{}
	}
	meta := req.Meta
	fillMeta(&meta)
	tags, slugMaps, err := pathcodec.GenerateChain(meta.CanonicalPath, req.ExistingSlugs)
	if err != nil {
		return nil, err
	}
	meta.Tags = tags
	r := &Rendition{meta: meta, slugMaps: slugMaps, manifestChat: req.ManifestChatID}
	if req.ManifestChatID == "" {
		// Legacy rows keep their td:v1 caption line so the in-channel record
		// stays parseable; the comment carrier never puts machine text on
		// captions (ADR 0018).
		r.caption, r.legacyReply, r.legacyNeedsReply, err = manifest.RenderLegacyCaption(meta, p.cfg.SafeMediaCaptionUTF16Units, p.cfg.MarginUTF16Units)
		if err != nil {
			return nil, err
		}
		return r, nil
	}
	capRes, err := manifest.RenderCaptionWithPrefix(meta, req.HumanPrefix, p.cfg.SafeMediaCaptionUTF16Units, p.cfg.MarginUTF16Units)
	if err != nil {
		return nil, err
	}
	r.caption = capRes.Caption
	return r, nil
}

// PublishFile completes a new ungrouped file: it sends the per-file manifest
// record and indexes the row as uploaded.
func (p *Publisher) PublishFile(ctx context.Context, req FileRequest) (*PublishResult, error) {
	r := req.Rendition
	manifestMsgID, _, err := p.writeRecord(ctx, req.ChannelID, req.MessageID, 0, r)
	if err != nil {
		return nil, telegram.MapError(err)
	}
	fileID, err := p.fileIndex.Index(ctx, indexRequest(req.ChannelRowID, req.FileID, req.MessageID, manifestMsgID, r, req.ReplaceFileID, true, p.now(req.Now)))
	if err != nil {
		return nil, apperr.Wrap(apperr.ErrDB, "publish file record", err)
	}
	return &PublishResult{FileID: fileID, ManifestMsgID: manifestMsgID}, nil
}

// PublishAlbum completes a new media group: it sends the group's one
// td-album:v1 inventory (ADR 0013) and indexes every member row in one
// transaction, so either the whole group is indexed or none of it is.
func (p *Publisher) PublishAlbum(ctx context.Context, req AlbumRequest) (*AlbumResult, error) {
	if len(req.Members) == 0 {
		return &AlbumResult{}, nil
	}
	manifestChat := req.Members[0].Rendition.manifestChat
	meta := manifest.AlbumMeta{GroupedID: req.GroupedID}
	for _, m := range req.Members {
		meta.Files = append(meta.Files, manifest.AlbumFileFromMeta(m.MessageID, m.Rendition.meta))
	}
	body, err := manifest.RenderAlbumReplyFitting(meta, manifest.DefaultTextBudget, p.cfg.MarginUTF16Units)
	if err != nil {
		return nil, err
	}
	inventoryID, err := telegram.NewManifestCarrier(p.tg, manifestChat).Send(ctx, req.ChannelID, req.Members[0].MessageID, body)
	if err != nil {
		return nil, telegram.MapError(err)
	}
	now := p.now(req.Now)
	reqs := make([]ports.FileIndexRequest, 0, len(req.Members))
	for _, m := range req.Members {
		reqs = append(reqs, indexRequest(req.ChannelRowID, m.FileID, m.MessageID, inventoryID, m.Rendition, m.ReplaceFileID, true, now))
	}
	res := &AlbumResult{InventoryMsgID: inventoryID}
	if err := p.fileIndex.IndexBatch(ctx, reqs); err != nil {
		return res, apperr.Wrap(apperr.ErrDB, "publish file record", err)
	}
	return res, nil
}

// Move rewrites an existing file's record and caption for its new metadata
// to and re-indexes it. When a Telegram write fails, the record is restored
// to from. The caption must follow the move: a caption that cannot be
// edited fails it.
func (p *Publisher) Move(ctx context.Context, ref RecordRef, from, to manifest.FileMeta, existingSlugs map[string]string) error {
	return p.rewrite(ctx, ref, to, from, existingSlugs, false)
}

// Repair re-applies an existing file's record and caption from meta and
// re-indexes it. A caption Telegram no longer lets td edit is left as is:
// the record alone carries the repair.
func (p *Publisher) Repair(ctx context.Context, ref RecordRef, meta manifest.FileMeta, existingSlugs map[string]string) error {
	return p.rewrite(ctx, ref, meta, meta, existingSlugs, true)
}

func (p *Publisher) rewrite(ctx context.Context, ref RecordRef, meta, restore manifest.FileMeta, existingSlugs map[string]string, tolerateNotEditable bool) error {
	if existingSlugs == nil {
		existingSlugs = map[string]string{}
	}
	r, err := p.Render(RenderRequest{Meta: meta, ManifestChatID: ref.ManifestChatID, ExistingSlugs: existingSlugs})
	if err != nil {
		return err
	}
	manifestMsgID, sent, err := p.writeRecord(ctx, ref.ChannelID, ref.MessageID, ref.ManifestMsgID, r)
	if err != nil {
		if err := p.restoreRecord(ctx, ref, manifestMsgID, sent, restore, existingSlugs); err != nil {
			return err
		}
		return telegram.MapError(err)
	}
	if err := p.tg.EditCaption(ctx, ref.ChannelID, ref.MessageID, r.caption); err != nil && (!tolerateNotEditable || !isNotEditable(err)) {
		if err := p.restoreRecord(ctx, ref, manifestMsgID, sent, restore, existingSlugs); err != nil {
			return err
		}
		return telegram.MapError(err)
	}
	if _, err := p.fileIndex.Index(ctx, indexRequest(ref.ChannelRowID, ref.FileID, ref.MessageID, manifestMsgID, r, 0, false, p.now(""))); err != nil {
		return apperr.Wrap(apperr.ErrDB, "publish file record", err)
	}
	return nil
}

// Reindex writes one file into the index without sending anything to
// Telegram.
func (p *Publisher) Reindex(ctx context.Context, req ReindexRequest) (*ReindexResult, error) {
	entry, err := p.PrepareReindex(req)
	if err != nil {
		return nil, err
	}
	fileID, err := p.fileIndex.Index(ctx, entry.req)
	if err != nil {
		return nil, apperr.Wrap(apperr.ErrDB, "reindex file record", err)
	}
	return &ReindexResult{FileID: fileID, ManifestMsgID: req.ManifestMsgID}, nil
}

// PrepareReindex renders one scanned file into an index entry (hashtag
// chain and slug maps) without writing anything. Its error is a rendering
// failure of this file alone, such as a slug collision.
func (p *Publisher) PrepareReindex(req ReindexRequest) (Reindexing, error) {
	if req.ExistingSlugs == nil {
		req.ExistingSlugs = map[string]string{}
	}
	meta := manifest.FileMeta{
		CanonicalPath: req.Meta.CanonicalPath,
		DisplayName:   req.Meta.DisplayName,
		ParentHuman:   fsmodel.HumanParent(req.Meta.CanonicalPath),
		Size:          req.Meta.Size,
		Hash:          req.Meta.Hash,
		MIME:          req.Meta.MIME,
		Created:       req.Meta.Created,
	}
	if meta.DisplayName == "" {
		meta.DisplayName = fsmodel.BaseName(meta.CanonicalPath)
	}
	tags, slugMaps, err := pathcodec.GenerateChain(meta.CanonicalPath, req.ExistingSlugs)
	if err != nil {
		return Reindexing{}, err
	}
	meta.Tags = tags
	return Reindexing{req: ports.FileIndexRequest{
		ChannelRowID:   req.ChannelRowID,
		FileID:         req.FileID,
		MessageID:      req.MessageID,
		ManifestMsgID:  req.ManifestMsgID,
		ManifestChatID: req.ManifestChatID,
		Meta:           meta,
		SlugMaps:       slugMaps,
		Tags:           tags,
		ReplaceFileID:  req.ReplaceFileID,
		SetUploadedAt:  req.FileID == 0,
		Now:            p.now(req.Now),
	}}, nil
}

// ReindexBatch commits prepared entries in one transaction. The index error
// is returned as is for the caller to classify.
func (p *Publisher) ReindexBatch(ctx context.Context, entries []Reindexing) error {
	reqs := make([]ports.FileIndexRequest, len(entries))
	for i, e := range entries {
		reqs[i] = e.req
	}
	return p.fileIndex.IndexBatch(ctx, reqs)
}

func indexRequest(channelRowID, fileID int64, messageID, manifestMsgID int, r *Rendition, replaceFileID int64, uploaded bool, now string) ports.FileIndexRequest {
	return ports.FileIndexRequest{
		ChannelRowID:   channelRowID,
		FileID:         fileID,
		MessageID:      messageID,
		ManifestMsgID:  manifestMsgID,
		ManifestChatID: r.manifestChat,
		Meta:           r.meta,
		SlugMaps:       r.slugMaps,
		Tags:           r.meta.Tags,
		ReplaceFileID:  replaceFileID,
		SetUploadedAt:  uploaded,
		Now:            now,
	}
}

// writeRecord sends or edits the per-file manifest record of a rendition
// through its carrier: always for the comment carrier, and for a legacy row
// whose td:v1 caption line does not fit or which already has a reply.
// manifestMsgID is the record's id afterwards (0 when none); sent reports a
// newly sent record.
func (p *Publisher) writeRecord(ctx context.Context, channelID int64, messageID, existingID int, r *Rendition) (manifestMsgID int, sent bool, err error) {
	carrier := telegram.NewManifestCarrier(p.tg, r.manifestChat)
	text := r.legacyReply
	if carrier.Comment() || !r.legacyNeedsReply {
		text = manifest.RenderManifestReplyFitting(r.meta, manifest.DefaultTextBudget, p.cfg.MarginUTF16Units)
	}
	switch {
	case existingID > 0:
		return existingID, false, carrier.Edit(ctx, channelID, existingID, text)
	case carrier.Comment(), r.legacyNeedsReply:
		id, err := carrier.Send(ctx, channelID, messageID, text)
		if err != nil {
			return 0, false, err
		}
		return id, true, nil
	default:
		return 0, false, nil
	}
}

// restoreRecord undoes writeRecord after a later failure: a newly sent
// record is deleted, an edited one is re-rendered from restore.
func (p *Publisher) restoreRecord(ctx context.Context, ref RecordRef, manifestMsgID int, sent bool, restore manifest.FileMeta, existingSlugs map[string]string) error {
	if manifestMsgID == 0 {
		return nil
	}
	carrier := telegram.NewManifestCarrier(p.tg, ref.ManifestChatID)
	if sent {
		if err := carrier.Delete(ctx, ref.ChannelID, manifestMsgID); err != nil && !isNotFound(err) {
			return telegram.MapError(err)
		}
		return nil
	}
	oldTags, _, err := pathcodec.GenerateChain(restore.CanonicalPath, existingSlugs)
	if err != nil {
		return err
	}
	restore.Tags = oldTags
	fillMeta(&restore)
	text := manifest.RenderManifestReplyFitting(restore, manifest.DefaultTextBudget, p.cfg.MarginUTF16Units)
	if err := carrier.Edit(ctx, ref.ChannelID, manifestMsgID, text); err != nil && !isNotEditable(err) && !isNotFound(err) {
		return telegram.MapError(err)
	}
	return nil
}

func fillMeta(m *manifest.FileMeta) {
	if m.DisplayName == "" {
		m.DisplayName = fsmodel.BaseName(m.CanonicalPath)
	}
	if m.ParentHuman == "" {
		m.ParentHuman = fsmodel.HumanParent(m.CanonicalPath)
	}
}

func isNotEditable(err error) bool {
	var e *telegram.MessageNotEditableError
	return errors.As(err, &e)
}

func isNotFound(err error) bool {
	var e *telegram.MessageNotFoundError
	return errors.As(err, &e)
}
