// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as gui$0 from "../../../../thedavidweng/tg-drive/internal/gui/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "auth.prompt": gui$0.AuthPrompt;
            "directory-changed": gui$0.DirectoryChanged;
            "files-dropped": gui$0.FilesDropped;
            "import.item": gui$0.ItemEvent;
            "import.prompt": gui$0.ImportPrompt;
            "omarchy:theme-changed": gui$0.OmarchyTheme;
            "repair.item": gui$0.ItemEvent;
            "scan-progress": gui$0.ScanProgress;
            "transfer-progress": gui$0.Transfer;
            "transfer-removed": gui$0.TransferRemoved;
            "transfer-stage": gui$0.Transfer;
        }
    }
}
