// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as gui$0 from "../../../../thedavidweng/tg-drive-cli/internal/gui/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "auth.prompt": gui$0.AuthPrompt;
            "omarchy:theme-changed": gui$0.OmarchyTheme;
        }
    }
}
