// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Auth is the facade service for Telegram setup, login, and logout.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnswerPrompt supplies the value for the pending prompt with the given ID.
 */
export function AnswerPrompt(id: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(3415606927, id, value);
}

/**
 * CancelPrompt aborts the pending prompt with the given ID, cancelling the
 * login that asked.
 */
export function CancelPrompt(id: string): $CancellablePromise<void> {
    return $Call.ByID(573068431, id);
}

/**
 * Login runs the interactive Telegram login. When the config has no phone
 * yet, phone is saved first (the login screen asks for it in that case).
 * forceNewCode requests a fresh code instead of reusing a pending one. The
 * login code and the 2FA password arrive as auth.prompt events and are
 * answered with AnswerPrompt.
 */
export function Login(phone: string, forceNewCode: boolean): $CancellablePromise<$models.LoginResult | null> {
    return $Call.ByID(2896932748, phone, forceNewCode);
}

/**
 * Logout logs the GUI session out. The saved credentials stay, so logging
 * in again only needs a new code.
 */
export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(852546681);
}

/**
 * Setup saves the API credentials and phone from the setup form through the
 * service's Telegram config setup, then reopens the App online and returns
 * the new status, so the frontend can move straight to login. All three
 * fields are required.
 */
export function Setup(apiID: string, apiHash: string, phone: string): $CancellablePromise<$models.AuthStatus | null> {
    return $Call.ByID(3953799672, apiID, apiHash, phone);
}

/**
 * Status reports the GUI session's setup and login state. An offline app
 * (no credentials yet) is simply unauthenticated.
 */
export function Status(): $CancellablePromise<$models.AuthStatus | null> {
    return $Call.ByID(1258278609);
}
