// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Channels is the facade service for the drives (Telegram channels) bound in
 * the shared index: listing them, binding or creating one, switching the
 * active one, and reporting a channel's status.
 * 
 * The App's channel selector is fixed at Open (service.Options.Channel), so
 * switching the active channel reopens the App bound to the new channel
 * (appState.switchChannel). The selection survives Auth's reopen the same
 * way.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Bind binds an existing Telegram channel as a drive, or creates a new drive
 * channel, through the service's init use case, and makes it the active
 * channel. GUI bindings use a synthetic per-channel local root under the
 * data directory.
 */
export function Bind(req: $models.BindRequest): $CancellablePromise<$models.BindResult | null> {
    return $Call.ByID(1609817859, req);
}

/**
 * Choices lists the user's Telegram channels with the ones already bound as
 * drives marked, plus the default title for a created channel.
 */
export function Choices(): $CancellablePromise<$models.BindChoices | null> {
    return $Call.ByID(2321931548);
}

/**
 * LinkDiscussion creates and links a discussion group for the active
 * channel when it has none (the service keeps an existing link), so the
 * channel can carry machine records (ADR 0018).
 */
export function LinkDiscussion(): $CancellablePromise<$models.DiscussionLink | null> {
    return $Call.ByID(3269868332);
}

/**
 * List returns the channels bound in the shared index, marking the active
 * one. It reads only the index, never Telegram, so it also works offline.
 */
export function List(): $CancellablePromise<$models.ChannelInfo[] | null> {
    return $Call.ByID(4263022068);
}

/**
 * Select switches the active channel: the App reopens bound to it, and every
 * facade call then works on that channel. The channel must be bound in the
 * index; an unknown ID fails with ERR_CHANNEL_NOT_FOUND and keeps the
 * current channel.
 */
export function Select(channelID: string): $CancellablePromise<$models.ChannelStatus | null> {
    return $Call.ByID(2032727796, channelID);
}

/**
 * Status reports the active channel's status. Without a bound channel it
 * fails with ERR_CHANNEL_NOT_FOUND.
 */
export function Status(): $CancellablePromise<$models.ChannelStatus | null> {
    return $Call.ByID(3734676182);
}
