// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Drive browses the bound channel's index.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete removes a remote file from Telegram and the index. Directories
 * cannot be deleted (file-level deletes only).
 */
export function Delete(path: string, opts: $models.DeleteOptions): $CancellablePromise<$models.DeleteOutcome | null> {
    return $Call.ByID(2894188476, path, opts);
}

/**
 * List lists the children of a remote directory from the local index,
 * directories first. It never contacts Telegram. The listed directory
 * becomes the one index sync re-reads and emits on EventDirectoryChanged.
 */
export function List(path: string): $CancellablePromise<$models.Entry[] | null> {
    return $Call.ByID(1946969127, path);
}

/**
 * Mkdir creates an empty directory in the virtual tree. Telegram cannot
 * store empty directories, so it is local-only until a file lands in it.
 */
export function Mkdir(path: string): $CancellablePromise<void> {
    return $Call.ByID(1005102246, path);
}

/**
 * Move renames a remote file or moves it into another directory of the
 * bound channel. Directories cannot move (file-level moves only).
 */
export function Move($from: string, to: string, opts: $models.MoveOptions): $CancellablePromise<void> {
    return $Call.ByID(317222262, $from, to, opts);
}

/**
 * Preview resolves the active file at path in the active channel into a
 * preview descriptor. It describes the file's Telegram representation once
 * (no body bytes) and prepares a media URL pinned to the file row. Preview
 * is an ephemeral read: no Transfer, operation lock, or history.
 */
export function Preview(path: string): $CancellablePromise<$models.PreviewDescriptor | null> {
    return $Call.ByID(3324997929, path);
}

/**
 * Scan rescans the bound channel from Telegram and rebuilds the local
 * index. While it runs it emits ScanProgress events; the final event
 * carries the completed counts.
 */
export function Scan(): $CancellablePromise<$models.ScanOutcome | null> {
    return $Call.ByID(1601550214);
}

/**
 * Share returns the invite link and legacy hashtag for a remote path.
 */
export function Share(path: string): $CancellablePromise<$models.ShareLink | null> {
    return $Call.ByID(3296790, path);
}

/**
 * Tree returns the directory tree below a remote path, up to maxDepth
 * levels (0 for the service default).
 */
export function Tree(path: string, maxDepth: number): $CancellablePromise<$models.TreeNode[] | null> {
    return $Call.ByID(3132039523, path, maxDepth);
}
