// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Import is the facade service for Saved Messages import.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnswerPrompt supplies the photo presentation for the pending prompt:
 * "document" or "photo".
 */
export function AnswerPrompt(id: string, choice: string): $CancellablePromise<void> {
    return $Call.ByID(3030541379, id, choice);
}

/**
 * CancelPrompt aborts the pending prompt, cancelling the import that asked.
 */
export function CancelPrompt(id: string): $CancellablePromise<void> {
    return $Call.ByID(2144106131, id);
}

/**
 * Preview plans the import without touching Telegram beyond reading the
 * saved chat. The photo choice, when the plan holds photos and PhotosAs is
 * empty, arrives as an import.prompt event here too, because the plan's
 * presentation depends on the answer.
 */
export function Preview(opts: $models.ImportOptions): $CancellablePromise<$models.ImportOutcome | null> {
    return $Call.ByID(74832301, opts);
}

/**
 * Run executes the import. Confirm is the frontend's confirmation sheet;
 * without it the service gate refuses with ERR_CONFIRMATION_REQUIRED, and
 * DeleteSource is refused even with a preview. A run continues past
 * per-item failures so the item list shows every outcome. While it runs it
 * emits ItemEvent on EventImportItem.
 */
export function Run(opts: $models.ImportOptions): $CancellablePromise<$models.ImportOutcome | null> {
    return $Call.ByID(3136803932, opts);
}
