// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Maintenance is the facade service for adopting channel messages,
 * repairing the drive, and the doctor diagnostics.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Adopt claims the channel's unmanaged messages into the index. Confirm is
 * the frontend's confirmation sheet; without it the service gate refuses
 * with ERR_CONFIRMATION_REQUIRED.
 */
export function Adopt(opts: $models.AdoptOptions): $CancellablePromise<$models.AdoptOutcome | null> {
    return $Call.ByID(879797616, opts);
}

/**
 * Doctor runs the service's capability checks: auth, storage, and the
 * Telegram probes (edit, delete, upload, invite, Saved Messages) — the
 * facade never reimplements a check.
 */
export function Doctor(): $CancellablePromise<$models.DoctorReport | null> {
    return $Call.ByID(389689345);
}

/**
 * PathCodecDoctor runs the path codec self-test and verifies the stored
 * slug mappings against the database.
 */
export function PathCodecDoctor(): $CancellablePromise<$models.PathCodecReport | null> {
    return $Call.ByID(3711706498);
}

/**
 * PreviewAdopt plans adopting the channel's unmanaged messages without
 * touching Telegram or the index.
 */
export function PreviewAdopt(opts: $models.AdoptOptions): $CancellablePromise<$models.AdoptOutcome | null> {
    return $Call.ByID(3397378852, opts);
}

/**
 * Repair runs the selected mode. While it runs it emits ItemEvent on
 * EventRepairItem once per item the mode accounts for.
 */
export function Repair(opts: $models.RepairOptions): $CancellablePromise<$models.RepairOutcome | null> {
    return $Call.ByID(3540652803, opts);
}
