// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings is the facade service for config and appearance preferences.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * List returns every config key in config-file order, secrets redacted.
 */
export function List(): $CancellablePromise<$models.ConfigEntry[] | null> {
    return $Call.ByID(3465956906);
}

/**
 * Omarchy reports whether td-gui runs on Omarchy with a current theme to
 * adopt, and that theme.
 */
export function Omarchy(): $CancellablePromise<$models.OmarchyState> {
    return $Call.ByID(3043176337);
}

/**
 * Reveal returns one config entry with its secret value shown. confirmed is
 * the frontend's explicit reveal click; without it the service's
 * confirmation gate refuses, and the refusal reaches the frontend.
 */
export function Reveal(key: string, confirmed: boolean): $CancellablePromise<$models.ConfigEntry> {
    return $Call.ByID(2177384963, key, confirmed);
}

/**
 * Set validates and saves one config key, returning the entry as it now
 * displays (a secret stays redacted).
 */
export function Set(key: string, value: string): $CancellablePromise<$models.ConfigEntry> {
    return $Call.ByID(596867238, key, value);
}

/**
 * Versions reports the version of both binaries. td and td-gui build from
 * one module stamped with one version at release, so the running binary's
 * stamp is the CLI's.
 */
export function Versions(): $CancellablePromise<$models.Versions> {
    return $Call.ByID(926113187);
}
