// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings is the facade service for config and appearance preferences.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * List returns every config key in config-file order, secrets redacted.
 */
export function List(): $CancellablePromise<$models.ConfigEntry[] | null> {
    return $Call.ByID(3465956906);
}

/**
 * Omarchy reports whether td-gui runs on Omarchy with a current theme to
 * adopt, and that theme.
 */
export function Omarchy(): $CancellablePromise<$models.OmarchyState> {
    return $Call.ByID(3043176337);
}

/**
 * Reveal returns one config entry with its secret value shown. confirmed is
 * the frontend's explicit reveal click; without it the service's
 * confirmation gate refuses, and the refusal reaches the frontend.
 */
export function Reveal(key: string, confirmed: boolean): $CancellablePromise<$models.ConfigEntry> {
    return $Call.ByID(2177384963, key, confirmed);
}

/**
 * Set validates and saves one config key, returning the entry as it now
 * displays (a secret stays redacted). transfers.concurrency applies to the
 * running Transfer queue at once; every other key applies the next time the
 * GUI starts, as it does for the next td command.
 */
export function Set(key: string, value: string): $CancellablePromise<$models.ConfigEntry> {
    return $Call.ByID(596867238, key, value);
}

/**
 * Versions reports the running GUI's stamp and the version of the td CLI
 * installed beside it. The two install separately, so the CLI's version
 * comes from running the td binary found on PATH or in the installers'
 * default directory; CLI is empty when none is found or it does not
 * answer `td version --json` like td does.
 */
export function Versions(): $CancellablePromise<$models.Versions> {
    return $Call.ByID(926113187);
}
