// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Transfers is the facade service over the Transfer Manager (ADR 0033):
 * every GUI upload and download runs as a Transfer, and the Transfers tab
 * watches them all, including the ones other front ends run. The facade
 * holds no Transfer state of its own beyond the last reported snapshot the
 * event stream dedupes against; the shared index is the record.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel requests a Transfer's cancellation through the index. It works on
 * any process's Transfer: the owner notices the flag on its lease
 * heartbeat and ends the Transfer cancelled.
 */
export function Cancel(id: string): $CancellablePromise<$models.Transfer | null> {
    return $Call.ByID(3718778370, id);
}

/**
 * ClearFinished removes every terminal Transfer from the index and reports
 * each removal as a transfer-removed event. It returns how many cleared.
 */
export function ClearFinished(): $CancellablePromise<number> {
    return $Call.ByID(3449147635);
}

/**
 * Download downloads a remote file or directory into the local directory
 * destDir, under the remote name, and returns the new Transfer's ID.
 */
export function Download(remotePath: string, destDir: string, opts: $models.DownloadOptions): $CancellablePromise<string> {
    return $Call.ByID(3375799640, remotePath, destDir, opts);
}

/**
 * List returns every Transfer in the index, split into active and history.
 * Reading marks Transfers whose owner vanished interrupted, as every
 * Manager reader does.
 */
export function List(): $CancellablePromise<$models.TransferList | null> {
    return $Call.ByID(1138066000);
}

/**
 * PickDirectory opens the native directory dialog, for the folder to
 * upload or the folder a download lands in. Without a connected picker it
 * is ERR_USAGE.
 */
export function PickDirectory(): $CancellablePromise<string> {
    return $Call.ByID(3864435356);
}

/**
 * PickFiles opens the native multi-file dialog. Without a connected picker
 * (a server-mode build without scripted answers) it is ERR_USAGE.
 */
export function PickFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1218515996);
}

/**
 * PlanUpload previews uploading paths into the remote directory dest under
 * policy, without starting anything: the service's dry-run plan plus each
 * file's size against the account's upload limit. It needs a logged-in
 * App for the limit, like the channel status does.
 */
export function PlanUpload(paths: string[] | null, dest: string, policy: string): $CancellablePromise<$models.UploadPlan | null> {
    return $Call.ByID(276795822, paths, dest, policy);
}

/**
 * Retry re-runs a failed, cancelled, or interrupted Transfer from its
 * recorded request; this GUI becomes its owner and an interrupted upload
 * resumes from its saved parts. The Manager pre-flights the stage from the
 * index and rejects active and completed Transfers with ERR_USAGE, as
 * td transfers retry does.
 */
export function Retry(id: string): $CancellablePromise<$models.Transfer | null> {
    return $Call.ByID(1115016106, id);
}

/**
 * Upload uploads local files and directories into the remote directory
 * dest (the one the Drive tab shows), and returns the new Transfers' IDs.
 * One file alone is a single-file Transfer; several files together are one
 * album Transfer; each directory is its own recursive Transfer, landing
 * under dest by its name. The mistakes the upload use cases would reject
 * mid-run — an unconfirmed replace, an album replace, an unknown policy or
 * presentation, presentation on a folder — fail fast here, before any
 * Transfer exists.
 * 
 * The Transfer outlives the call: the bound method's ctx ends when Upload
 * returns, so the Transfer runs under a ctx bounded only by the process.
 */
export function Upload(paths: string[] | null, dest: string, opts: $models.UploadOptions): $CancellablePromise<string[] | null> {
    return $Call.ByID(1508530233, paths, dest, opts);
}
