// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Drive browses the bound channel's index.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * List lists the children of a remote directory from the local index,
 * directories first. It never contacts Telegram.
 */
export function List(path: string): $CancellablePromise<$models.Entry[] | null> {
    return $Call.ByID(2300287016, path);
}
