// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AdoptItem is one channel message in a preview or a result.
 */
export interface AdoptItem {
    "message_id": number;
    "kind": string;
    "file_name"?: string;
    "path"?: string;
    "size"?: number;

    /**
     * Action is "adopt", "restore", "skip", or "fail".
     */
    "action": string;
    "reason"?: string;
}

/**
 * AdoptOptions carries one adopt's settings. Confirm is the typed
 * confirmation the real adopt requires (ADR 0003); a preview needs none.
 */
export interface AdoptOptions {
    /**
     * Into is the directory adopted messages land in (the drive root when
     * empty).
     */
    "into"?: string;

    /**
     * NoHash adopts without downloading the content hash.
     */
    "no_hash"?: boolean;

    /**
     * RewriteCaptions restores captions from the machine records instead of
     * adopting new messages.
     */
    "rewrite_captions"?: boolean;
    "confirm"?: boolean;
}

/**
 * AdoptOutcome is the dry-run plan or the finished adopt's summary.
 */
export interface AdoptOutcome {
    "dry_run": boolean;
    "adopted": number;
    "skipped": number;
    "failed": number;
    "deleted": number;
    "items": AdoptItem[] | null;
}

/**
 * AuthPrompt is the auth.prompt event payload: login needs an answer from
 * the user. The frontend answers with Auth.AnswerPrompt (or Auth.CancelPrompt)
 * using the prompt's ID.
 */
export interface AuthPrompt {
    "id": string;
    "kind": string;

    /**
     * Attempt is the 1-based entry attempt for the current code or password.
     */
    "attempt": number;

    /**
     * MaxAttempts bounds code attempts; 0 when the flow does not say
     * (password prompts).
     */
    "max_attempts": number;

    /**
     * Reused is true when the prompt is for a code sent by an earlier login,
     * Resent when a fresh code was just sent because the previous one
     * expired.
     */
    "reused": boolean;
    "resent": boolean;

    /**
     * SentAt is when the code was sent (RFC 3339), empty when unknown.
     */
    "sent_at"?: string;
}

/**
 * AuthStatus is what the shell needs to choose between the setup, login,
 * and main screens.
 */
export interface AuthStatus {
    /**
     * Configured is true when api_id and api_hash are saved.
     */
    "configured": boolean;

    /**
     * HasPhone is true when a phone number is saved; the login screen asks
     * for one when it is not.
     */
    "has_phone": boolean;
    "authenticated": boolean;
    "user"?: AuthUser | null;
}

/**
 * AuthUser identifies the logged-in Telegram account.
 */
export interface AuthUser {
    "display_name": string;
    "phone": string;
    "user_id": number;
}

/**
 * BindChoices is what the bind dialog offers: the user's Telegram channels,
 * and the default title for a created one.
 */
export interface BindChoices {
    "channels": ChannelChoice[] | null;
    "default_title": string;
}

/**
 * BindRequest is one bind-or-create decision from the bind dialog. ChannelID
 * binds that existing Telegram channel; with ChannelID empty a new drive
 * channel is created, titled Title, or the default title when Title is
 * empty.
 */
export interface BindRequest {
    "channel_id": string;
    "title": string;
}

/**
 * BindResult reports a finished bind or creation. The bound channel becomes
 * the active one.
 */
export interface BindResult {
    "channel_id": string;
    "title": string;

    /**
     * Created is true when a new Telegram channel was created; false when
     * an existing one was bound.
     */
    "created": boolean;

    /**
     * AlreadyInitialized is true when this GUI already bound the channel's
     * local root; nothing was created or changed.
     */
    "already_initialized": boolean;

    /**
     * IndexedFiles is how many existing files binding the channel indexed;
     * absent when the initial scan did not run or failed.
     */
    "indexed_files"?: number | null;

    /**
     * ScanError carries the initial scan's failure; the binding is usable
     * and a rescan retries it.
     */
    "scan_error"?: string;
}

export interface CaptionsRepairOutcome {
    "dry_run": boolean;
    "total": number;
    "planned": number;
    "cleaned": number;
    "skipped": number;
    "failed": number;
    "items": RepairItem[] | null;
}

/**
 * ChannelChoice is one Telegram channel the bind dialog offers, marked when
 * it is already bound as a drive.
 */
export interface ChannelChoice {
    /**
     * ChannelID is the channel's Telegram ID.
     */
    "channel_id": string;
    "title": string;
    "bound": boolean;
}

/**
 * ChannelInfo is one channel bound in the shared index (td init or a GUI
 * bind), as the header switcher lists it.
 */
export interface ChannelInfo {
    /**
     * ChannelID is the channel's Telegram ID, and the selector Select takes.
     */
    "channel_id": string;
    "title": string;

    /**
     * LocalRoot is the local root the channel is bound to. GUI bindings use
     * a synthetic root per channel under the data directory; it is a label,
     * never created on disk.
     */
    "local_root": string;

    /**
     * Active marks the channel every facade call currently works on.
     */
    "active": boolean;
}

/**
 * ChannelStatus is the active channel's health: its linked discussion group,
 * its capabilities, and the index's freshness (ADR 0018, `td status`).
 */
export interface ChannelStatus {
    "channel_id": string;
    "title": string;
    "local_root": string;

    /**
     * Files is how many active files the index holds for the channel.
     */
    "files": number;

    /**
     * DiscussionLinked reports whether a discussion group carries the
     * channel's machine records; DiscussionTitle names it when linked.
     */
    "discussion_linked": boolean;
    "discussion_title"?: string;

    /**
     * UploadLimitBytes is the account's per-file upload limit on Telegram.
     */
    "upload_limit_bytes": number;

    /**
     * LastScanAt is the RFC3339 time the index last changed from a scan,
     * empty when the channel was never scanned; LastFullScanAt is the last
     * completed full scan.
     */
    "last_scan_at"?: string;
    "last_full_scan_at"?: string;
}

/**
 * ChannelsChanged is the payload of EventChannelsChanged: the bound
 * channels as Channels.List returns them.
 */
export interface ChannelsChanged {
    "channels": ChannelInfo[] | null;
}

/**
 * ConfigEntry is one config key and its display value.
 */
export interface ConfigEntry {
    "key": string;

    /**
     * Value is redacted unless the caller revealed the secret.
     */
    "value": any;
    "secret": boolean;

    /**
     * RestartRequired marks a saved key the running GUI cannot apply: one
     * its Telegram client or database was opened with. It takes effect
     * when td-gui next starts; every other key applies at once.
     */
    "restart_required"?: boolean;
}

/**
 * DeleteOptions carries the delete's typed confirmation (ADR 0003). An
 * unconfirmed delete is rejected with ERR_CONFIRMATION_REQUIRED.
 */
export interface DeleteOptions {
    "confirm": boolean;
}

/**
 * DeleteOutcome reports how a file was removed.
 */
export interface DeleteOutcome {
    /**
     * Mode is the configured delete mode that ran (e.g. "delete" or
     * "tombstone").
     */
    "mode": string;
    "path": string;
}

/**
 * DirectoryChanged is the payload of EventDirectoryChanged: the refreshed
 * listing of the directory the frontend is showing.
 */
export interface DirectoryChanged {
    "path": string;
    "entries": Entry[] | null;
}

/**
 * DiscussionLink identifies the discussion group a LinkDiscussion call
 * linked to the active channel.
 */
export interface DiscussionLink {
    "discussion_channel_id": string;
    "discussion_title": string;
}

/**
 * DoctorCheck is one capability check's outcome.
 */
export interface DoctorCheck {
    "name": string;

    /**
     * Status is "pass", "warn", "fail", or "unknown".
     */
    "status": string;

    /**
     * Hint is how to fix a warn or fail, when the check has one.
     */
    "hint"?: string;
}

/**
 * DoctorReport is the doctor run rendered for the frontend: the checks in
 * name order plus the upload limit the Telegram probe reported.
 */
export interface DoctorReport {
    "checks": DoctorCheck[] | null;
    "max_upload_bytes"?: number | null;
}

/**
 * DownloadOptions are the download sheet's choices.
 */
export interface DownloadOptions {
    /**
     * Policy is the local conflict policy: "skip", "replace", or "fail"
     * (the zero value, matching get without flags).
     */
    "policy": string;
}

/**
 * Entry is one row of a directory listing.
 */
export interface Entry {
    "name": string;
    "path": string;

    /**
     * Type is "dir" or "file".
     */
    "type": string;

    /**
     * Size is in bytes; 0 for directories.
     */
    "size": number;

    /**
     * Date is the RFC3339 time the file or directory last changed.
     */
    "date": string;
}

/**
 * FilesDropped is the payload of EventFilesDropped: the absolute local
 * paths the OS reported for the drop. cmd/td-gui translates the window's
 * native drop event into it; the facade itself never sees the window.
 */
export interface FilesDropped {
    "paths": string[] | null;
}

export interface HashRepairOutcome {
    "total": number;
    "backfilled": number;
    "failed": number;
    "items": RepairItem[] | null;
}

/**
 * ImportItem is one saved message in a preview or a result.
 */
export interface ImportItem {
    "message_id": number;
    "kind": string;

    /**
     * Action is "import", "skip", or "fail".
     */
    "action": string;
    "path"?: string;
    "size"?: number;
    "reason"?: string;

    /**
     * DuplicateOf names the drive file whose bytes matched a skipped item.
     */
    "duplicate_of"?: string;

    /**
     * SourceDeleted reports the saved original was deleted.
     */
    "source_deleted"?: boolean;
    "error"?: string;
}

/**
 * ImportOptions carries one import's settings. Confirm is the typed
 * confirmation the real run requires (ADR 0003); DeleteSource requires it
 * even on a preview. An empty PhotosAs asks through EventImportPrompt when
 * the plan holds photos.
 */
export interface ImportOptions {
    /**
     * Into is the destination directory (the service default when empty).
     */
    "into"?: string;

    /**
     * PhotosAs is "document" or "photo"; empty asks via import.prompt.
     */
    "photos_as"?: string;

    /**
     * Policy resolves destination path conflicts: "fail" (the default),
     * "replace", "skip", or "rename".
     */
    "policy"?: string;
    "merge_captions"?: boolean;
    "delete_source"?: boolean;
    "no_dedupe"?: boolean;
    "confirm"?: boolean;
}

/**
 * ImportOutcome is the dry-run plan or the finished run's summary.
 */
export interface ImportOutcome {
    "dry_run": boolean;
    "into": string;
    "photos_as"?: string;
    "history_complete": boolean;
    "imported": number;
    "skipped": number;
    "failed": number;
    "duplicates": number;
    "captions_merged": number;
    "sources_deleted": number;
    "photos": number;
    "items": ImportItem[] | null;
}

/**
 * ImportPrompt is the import.prompt event payload. The photo presentation
 * has no safe default (documents keep the bytes, native photos are
 * recompressed), so an import that meets photos without a choice asks.
 */
export interface ImportPrompt {
    "id": string;

    /**
     * Kind is PromptPhotos, the only import prompt.
     */
    "kind": string;

    /**
     * Photos is how many photo messages wait on the answer.
     */
    "photos": number;
}

/**
 * ItemEvent is the import.item and repair.item payload: one item's outcome
 * plus the running tally, so the frontend renders item-by-item progress.
 */
export interface ItemEvent {
    "path"?: string;
    "message_id"?: number;

    /**
     * Status is "completed", "skipped", or "failed" (service.ItemStatus).
     */
    "status": string;

    /**
     * Error is why a failed item failed.
     */
    "error"?: string;
    "completed": number;
    "skipped": number;
    "failed": number;
}

/**
 * LoginResult reports a completed login.
 */
export interface LoginResult {
    "already_authenticated": boolean;
    "user": AuthUser;
}

/**
 * MoveOptions carries the move's typed confirmation (ADR 0003). An
 * unconfirmed move is rejected with ERR_CONFIRMATION_REQUIRED.
 */
export interface MoveOptions {
    "confirm": boolean;
}

/**
 * OmarchyState is whether the Omarchy look applies, and the theme to draw
 * it with.
 */
export interface OmarchyState {
    "available": boolean;
    "theme"?: OmarchyTheme | null;
}

/**
 * OmarchyTheme is the current Omarchy theme as the frontend draws with it.
 */
export interface OmarchyTheme {
    /**
     * tokyo-night
     */
    "name": string;

    /**
     * dark or light
     */
    "mode": string;

    /**
     * changes when any of it does
     */
    "stamp": string;

    /**
     * CSS custom properties
     */
    "vars": { [_ in string]?: string } | null;
}

export interface OrphanedRepairOutcome {
    "repaired": number;
    "deleted": number;
    "invalid": number;
}

/**
 * PathCodecReport is the path-codec doctor's result.
 */
export interface PathCodecReport {
    "fixed_vectors": string;
    "db_check": string;
    "db_rows": number;
    "corrupt_rows": number;
}

export interface PathRepairOutcome {
    "repaired": string;
}

export interface PendingRepairOutcome {
    "repaired": number;
    "invalid": number;
    "orphaned": number;
    "skipped": number;
    "locks_cleared": number;
}

/**
 * RepairItem is one file a captions or hash repair touched.
 */
export interface RepairItem {
    "path": string;
    "message_id"?: number;
    "action": string;
    "reason"?: string;
}

/**
 * RepairOptions selects one repair mode and its settings. Path is required
 * for "path" and scopes "captions" and "hash"; it is ignored by the other
 * modes. DeleteOrphaned (orphaned mode only) requires Confirm (ADR 0003).
 * DryRun and ContinueOnError apply to captions only.
 */
export interface RepairOptions {
    "mode": string;
    "path"?: string;
    "delete_orphaned"?: boolean;
    "confirm"?: boolean;
    "dry_run"?: boolean;
    "continue_on_error"?: boolean;
}

/**
 * RepairOutcome is the selected mode's result; exactly one field beyond
 * Mode is set.
 */
export interface RepairOutcome {
    "mode": string;
    "captions"?: CaptionsRepairOutcome | null;
    "hash"?: HashRepairOutcome | null;
    "path"?: PathRepairOutcome | null;
    "pending"?: PendingRepairOutcome | null;
    "orphaned"?: OrphanedRepairOutcome | null;
    "scan_errors"?: ScanErrorsRepairOutcome | null;
}

export interface ScanErrorsRepairOutcome {
    "resolved": number;
    "pending": number;
}

/**
 * ScanOutcome reports a completed rescan.
 */
export interface ScanOutcome {
    "mode": string;
    "active": number;
    "deleted": number;
    "invalid": number;
    "missing": number;
}

/**
 * ScanProgress is the payload of EventScanProgress.
 */
export interface ScanProgress {
    /**
     * Stage is the scan's current stage: "reading" or "indexing".
     */
    "stage": string;

    /**
     * Indexed is how many files the scan has indexed so far.
     */
    "indexed": number;

    /**
     * Failed is how many scan errors the scan has recorded so far.
     */
    "failed": number;
}

/**
 * ShareLink is what a person needs to open a path on Telegram.
 */
export interface ShareLink {
    /**
     * URL is the bound channel's invite link.
     */
    "url": string;

    /**
     * Hashtag locates the file inside the channel; empty when unknown.
     */
    "hashtag"?: string;
    "path": string;
    "channel": string;
}

/**
 * Transfer is one Transfer as the frontend sees it: the index record with
 * RFC3339 timestamps.
 */
export interface Transfer {
    "id": string;
    "kind": string;
    "stage": string;

    /**
     * Channel is the Telegram ID of the drive channel the Transfer works
     * on.
     */
    "channel": string;
    "source": string;
    "dest": string;

    /**
     * BytesDone and BytesTotal track single-file Transfers; multi-item
     * kinds count items instead.
     */
    "bytes_done": number;
    "bytes_total": number;
    "items_done": number;
    "items_total": number;

    /**
     * ItemsFailed is omitted when nothing failed.
     */
    "items_failed"?: number;

    /**
     * ErrorCode and ErrorMessage are the failure a failed Transfer ended
     * with: the envelope's code and its plain-language message.
     */
    "error_code"?: string;
    "error_message"?: string;
    "front_end": string;
    "cancel_requested": boolean;
    "created_at": string;
    "updated_at": string;

    /**
     * FinishedAt is empty while the Transfer runs.
     */
    "finished_at"?: string;
}

/**
 * TransferList is the Transfers tab's data: the active Transfers above the
 * history of the last 30 days (the index prunes older terminal Transfers),
 * each newest first.
 */
export interface TransferList {
    "active": Transfer[] | null;
    "history": Transfer[] | null;
}

/**
 * TransferRemoved is the payload of EventTransferRemoved.
 */
export interface TransferRemoved {
    "id": string;
}

/**
 * TreeNode is one node of a directory tree.
 */
export interface TreeNode {
    "name": string;
    "path": string;
    "type": string;
    "children"?: TreeNode[] | null;
}

/**
 * UploadOptions are the upload sheet's choices. They map one-to-one onto
 * the service's upload options: the conflict policy and the replace
 * confirmation (service.UploadOptions.Validate), the presentation kind and
 * caption (service.Presentation, UploadOptions.Caption), and the recursive
 * switches of td cp --recursive.
 */
export interface UploadOptions {
    /**
     * Policy is the remote conflict policy: "skip", "replace", or "fail"
     * (the zero value, matching cp without flags). The CLI-only rename
     * policy is not offered.
     */
    "policy": string;

    /**
     * ConfirmReplace is the ADR 0003 confirmation Policy "replace"
     * requires.
     */
    "confirm_replace"?: boolean;

    /**
     * Kind is the Telegram presentation: "document", "photo", or "video"
     * ("" is the document default). Folder uploads take no presentation.
     */
    "kind"?: string;

    /**
     * Caption is human text rendered above the caption block: on the file's
     * own message for one file, on the first member of an album. Folder
     * uploads take no caption.
     */
    "caption"?: string;

    /**
     * NoHash skips content hashing (cp --no-hash).
     */
    "no_hash"?: boolean;

    /**
     * ContinueOnError lets a folder upload continue past failed files
     * (cp --continue-on-error).
     */
    "continue_on_error"?: boolean;

    /**
     * IncludeEmptyDirs asks a folder upload to create empty directories (cp
     * --include-empty-dirs); the service answers with its typed V1 error.
     */
    "include_empty_dirs"?: boolean;
}

/**
 * UploadPlan is the dry-run preview the upload sheet shows before the
 * upload starts. Local, Remote, Policy, and WouldReplace are the service's
 * dry-run plan for the same input, exactly as td cp --dry-run reports it;
 * the rest lets the sheet show what the bare plan cannot.
 */
export interface UploadPlan {
    "local": string[] | null;
    "remote": string;
    "policy": string;
    "would_replace"?: string;

    /**
     * UploadLimitBytes is the account's per-file upload limit (2 GB, or
     * 4 GB with Premium), from the same capability surface as td status.
     */
    "upload_limit_bytes": number;

    /**
     * Files carries one entry per path, in the order given.
     */
    "files": UploadPlanFile[] | null;
}

/**
 * UploadPlanFile is one local path in the upload plan preview.
 */
export interface UploadPlanFile {
    "local": string;

    /**
     * Size is the file's size; 0 for folders and paths that do not stat.
     */
    "size": number;

    /**
     * Dir marks a folder (a recursive upload).
     */
    "dir"?: boolean;

    /**
     * OverLimit marks a file larger than the account's upload limit; the
     * upload itself would fail with ERR_FILE_TOO_LARGE.
     */
    "over_limit"?: boolean;
}

/**
 * Versions are the versions the About rows show.
 */
export interface Versions {
    "gui": string;
    "cli": string;
}
