// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthPrompt is the auth.prompt event payload: login needs an answer from
 * the user. The frontend answers with Auth.AnswerPrompt (or Auth.CancelPrompt)
 * using the prompt's ID.
 */
export interface AuthPrompt {
    "id": string;
    "kind": string;

    /**
     * Attempt is the 1-based entry attempt for the current code or password.
     */
    "attempt": number;

    /**
     * MaxAttempts bounds code attempts; 0 when the flow does not say
     * (password prompts).
     */
    "max_attempts": number;

    /**
     * Reused is true when the prompt is for a code sent by an earlier login,
     * Resent when a fresh code was just sent because the previous one
     * expired.
     */
    "reused": boolean;
    "resent": boolean;

    /**
     * SentAt is when the code was sent (RFC 3339), empty when unknown.
     */
    "sent_at"?: string;
}

/**
 * AuthStatus is what the shell needs to choose between the setup, login,
 * and main screens.
 */
export interface AuthStatus {
    /**
     * Configured is true when api_id and api_hash are saved.
     */
    "configured": boolean;

    /**
     * HasPhone is true when a phone number is saved; the login screen asks
     * for one when it is not.
     */
    "has_phone": boolean;
    "authenticated": boolean;
    "user"?: AuthUser | null;
}

/**
 * AuthUser identifies the logged-in Telegram account.
 */
export interface AuthUser {
    "display_name": string;
    "phone": string;
    "user_id": number;
}

/**
 * ConfigEntry is one config key and its display value.
 */
export interface ConfigEntry {
    "key": string;

    /**
     * Value is redacted unless the caller revealed the secret.
     */
    "value": any;
    "secret": boolean;
}

/**
 * DeleteOptions carries the delete's typed confirmation (ADR 0003). An
 * unconfirmed delete is rejected with ERR_CONFIRMATION_REQUIRED.
 */
export interface DeleteOptions {
    "confirm": boolean;
}

/**
 * DeleteOutcome reports how a file was removed.
 */
export interface DeleteOutcome {
    /**
     * Mode is the configured delete mode that ran (e.g. "delete" or
     * "tombstone").
     */
    "mode": string;
    "path": string;
}

/**
 * DirectoryChanged is the payload of EventDirectoryChanged: the refreshed
 * listing of the directory the frontend is showing.
 */
export interface DirectoryChanged {
    "path": string;
    "entries": Entry[] | null;
}

/**
 * Entry is one row of a directory listing.
 */
export interface Entry {
    "name": string;
    "path": string;

    /**
     * Type is "dir" or "file".
     */
    "type": string;

    /**
     * Size is in bytes; 0 for directories.
     */
    "size": number;

    /**
     * Date is the RFC3339 time the file or directory last changed.
     */
    "date": string;
}

/**
 * LoginResult reports a completed login.
 */
export interface LoginResult {
    "already_authenticated": boolean;
    "user": AuthUser;
}

/**
 * MoveOptions carries the move's typed confirmation (ADR 0003). An
 * unconfirmed move is rejected with ERR_CONFIRMATION_REQUIRED.
 */
export interface MoveOptions {
    "confirm": boolean;
}

/**
 * OmarchyState is whether the Omarchy look applies, and the theme to draw
 * it with.
 */
export interface OmarchyState {
    "available": boolean;
    "theme"?: OmarchyTheme | null;
}

/**
 * OmarchyTheme is the current Omarchy theme as the frontend draws with it.
 */
export interface OmarchyTheme {
    /**
     * tokyo-night
     */
    "name": string;

    /**
     * dark or light
     */
    "mode": string;

    /**
     * changes when any of it does
     */
    "stamp": string;

    /**
     * CSS custom properties
     */
    "vars": { [_ in string]?: string } | null;
}

/**
 * ScanOutcome reports a completed rescan.
 */
export interface ScanOutcome {
    "mode": string;
    "active": number;
    "deleted": number;
    "invalid": number;
    "missing": number;
}

/**
 * ScanProgress is the payload of EventScanProgress.
 */
export interface ScanProgress {
    /**
     * Stage is the scan's current stage: "reading" or "indexing".
     */
    "stage": string;

    /**
     * Indexed is how many files the scan has indexed so far.
     */
    "indexed": number;

    /**
     * Failed is how many scan errors the scan has recorded so far.
     */
    "failed": number;
}

/**
 * ShareLink is what a person needs to open a path on Telegram.
 */
export interface ShareLink {
    /**
     * URL is the bound channel's invite link.
     */
    "url": string;

    /**
     * Hashtag locates the file inside the channel; empty when unknown.
     */
    "hashtag"?: string;
    "path": string;
    "channel": string;
}

/**
 * TreeNode is one node of a directory tree.
 */
export interface TreeNode {
    "name": string;
    "path": string;
    "type": string;
    "children"?: TreeNode[] | null;
}

/**
 * Versions are the versions the About rows show.
 */
export interface Versions {
    "gui": string;
    "cli": string;
}
