// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Entry is one row of a directory listing.
 */
export interface Entry {
    "name": string;
    "path": string;

    /**
     * Type is "dir" or "file".
     */
    "type": string;

    /**
     * Size is in bytes; 0 for directories.
     */
    "size": number;
}
