// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings is the facade service for config and appearance preferences. It
 * reads and writes the config file the CLI shares, so it opens with no
 * GUI-specific overrides: the GUI's own session path never reaches the
 * file.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * List returns every config key in config-file order, secrets redacted.
 */
export function List(): $CancellablePromise<$models.ConfigEntry[] | null> {
    return $Call.ByID(3640722555);
}

/**
 * Omarchy reports whether td-gui runs on Omarchy with a current theme to
 * adopt, and that theme.
 */
export function Omarchy(): $CancellablePromise<$models.OmarchyState> {
    return $Call.ByID(1427116634);
}

/**
 * Reveal returns one config entry with its secret value shown. confirmed is
 * the frontend's explicit reveal click; without it the service's
 * confirmation gate refuses, and the refusal reaches the frontend.
 */
export function Reveal(key: string, confirmed: boolean): $CancellablePromise<$models.ConfigEntry> {
    return $Call.ByID(169765862, key, confirmed);
}

/**
 * Set validates and saves one config key, returning the entry as it now
 * displays (a secret stays redacted), and applies it to the running GUI
 * unless it is RestartRequired.
 */
export function Set(key: string, value: string): $CancellablePromise<$models.ConfigEntry> {
    return $Call.ByID(2872150865, key, value);
}

/**
 * Versions reports td-gui's own version and that of the td CLI installed
 * beside it. The two install separately, so the CLI's version is asked of
 * the td binary itself; CLI is empty when none is found or it does not
 * answer.
 */
export function Versions(): $CancellablePromise<$models.Versions> {
    return $Call.ByID(2711480090);
}
